"""Authoritative catalogue of stable, public application error codes."""

from enum import StrEnum


class ErrorCode(StrEnum):
    """Identify a client-safe failure without exposing implementation details."""

    VALIDATION_ERROR = "VALIDATION_ERROR"
    INVALID_LOGIN = "INVALID_LOGIN"
    INVALID_TOKEN = "INVALID_TOKEN"  # noqa: S105 - public error identifier
    SESSION_EXPIRED = "SESSION_EXPIRED"
    SESSION_REVOKED = "SESSION_REVOKED"
    USER_DISABLED = "USER_DISABLED"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    CONVERSATION_NOT_FOUND = "CONVERSATION_NOT_FOUND"
    GROUP_NOT_FOUND = "GROUP_NOT_FOUND"
    MESSAGE_NOT_FOUND = "MESSAGE_NOT_FOUND"
    MESSAGE_TOO_LONG = "MESSAGE_TOO_LONG"
    MESSAGE_CONFLICT = "MESSAGE_CONFLICT"
    ATTACHMENT_NOT_FOUND = "ATTACHMENT_NOT_FOUND"
    ATTACHMENT_TOO_LARGE = "ATTACHMENT_TOO_LARGE"
    NOT_CONVERSATION_MEMBER = "NOT_CONVERSATION_MEMBER"
    NOT_GROUP_MEMBER = "NOT_GROUP_MEMBER"
    INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    UNSUPPORTED_PROTOCOL = "UNSUPPORTED_PROTOCOL"
    UNSUPPORTED_ALGORITHM = "UNSUPPORTED_ALGORITHM"
    INVALID_ENVELOPE = "INVALID_ENVELOPE"
    CONFLICT = "CONFLICT"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    INTERNAL_ERROR = "INTERNAL_ERROR"
