"""Authoritative WebSocket event-type catalogue."""

from enum import StrEnum


class WebSocketEventType(StrEnum):
    """Identify every Version 1 WebSocket event payload."""

    AUTHENTICATE = "AUTHENTICATE"
    AUTHENTICATED = "AUTHENTICATED"
    HEARTBEAT = "HEARTBEAT"
    MESSAGE_RECEIVED = "MESSAGE_RECEIVED"
    MESSAGE_UPDATED = "MESSAGE_UPDATED"
    MESSAGE_DELETED = "MESSAGE_DELETED"
    MESSAGE_DELIVERED = "MESSAGE_DELIVERED"
    MESSAGE_READ = "MESSAGE_READ"
    TYPING_CHANGED = "TYPING_CHANGED"
    PRESENCE_CHANGED = "PRESENCE_CHANGED"
    GROUP_MEMBER_ADDED = "GROUP_MEMBER_ADDED"
    GROUP_MEMBER_REMOVED = "GROUP_MEMBER_REMOVED"
    SESSION_REVOKED = "SESSION_REVOKED"
    ANNOUNCEMENT_PUBLISHED = "ANNOUNCEMENT_PUBLISHED"
    POLICY_UPDATED = "POLICY_UPDATED"
    SERVER_SHUTDOWN = "SERVER_SHUTDOWN"
    ERROR = "ERROR"
